Modificacion de panel de naveacion, ventana de clientes y tokens
Desarrollo-Aplicaciones-Web-UJCV/front-end pull request #31
Opened 2021-12-04 12:02 UTC by Jossep10

modificaciones que se me asignaron

2021-12-05 16:15 UTC, frankujcv requested changes
- Algunos enlaces a mi no me funcionan aun. Pero esperá la review de  @JBRIZO por si es cuestión de mi ambiente.
- En un comentario aparte te voy a dejar videos para que empeces a investigar como se hace lo de las consulta, Pero tenes que ponerte a investigar por tu cuenta.
- Algo hiciste en compras que no se leen las compras en mostrarCompras. ni los usuarios en mostrarUsuarios ni productos en  mostrarProductos.

2021-12-05 16:22 UTC, frankujcv commented
@Jossep10 https://youtu.be/hioDMKdJhwQ

2021-12-05 17:45 UTC, JBRIZO requested changes
- Falta uno que otro enlace todavía.
- No muestra compras, ni usuarios ni productos

2021-12-06 07:45 UTC, frankujcv reviewed
Lo siento man. No podemos meter esto a main. No funciona.

2021-12-06 07:45 UTC, closed without merging